BlogSite/urls.py
from django.contrib import admin
from django.urls import path, include
from BlogSite import settings
from django.conf.urls.static import static

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('blog.urls')),
    path('users/', include('users.urls')),
]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root= settings.MEDIA_ROOT)

handler404 = "blog.views.page_not_found"
handler403 = "blog.views.forbidden"
handler500 = "blog.views.server_error"

blog/urls.py
from django.urls import path
from blog.views import index, about, add_post, read_post, update_post,delete_post,about_blog

app_name = 'blog'
urlpatterns = [
    path('about/', about, name='about'),
    path('about_blog/', about_blog, name='about_blog'),
    path('post/<int:pk>/delete/', delete_post, name='delete_post'),
    path('post/<int:pk>/edit/', update_post, name='update_post'),
    path('post/<slug:slug>/', read_post, name='read_post'),
    path('post/', add_post, name='add_post'),
    path('', index, name='index'),
]

users/urls.py
from django.urls import path
from .views import register,log_in,log_out,user_profile

app_name = 'blog'
urlpatterns = [
    path('register/', register, name='register'),
    path('login/', log_in, name='login'),
    path('logout/', log_out, name='logout'),
    path('profile/<int:pk>/', user_profile, name='profile'),
]

blog/models.py
from django.db import models
from django.utils import timezone
from django.urls import reverse
from django.contrib.auth.models import User
from slugify import slugify


#Описание модели поста
class Post(models.Model):
    title = models.CharField(max_length=200, verbose_name="Загаловок")
    text = models.TextField(verbose_name="Текст поста")
    created_at = models.DateTimeField(default=timezone.now, verbose_name="Дата создания", editable=False)
    author = models.ForeignKey(User, on_delete=models.CASCADE, verbose_name="Автор")
    image = models.ImageField(upload_to='post/', null=True, verbose_name="Избражение")
    slug = models.SlugField(max_length=200, unique=True, editable=False,null=True)

    def save(self, *args, **kwargs):
        self.slug = slugify(self.title)
        super().save(*args, **kwargs)

    def get_absolute_url(self):
        return  reverse('blog:read_post', kwargs={'slug':self.slug})


    class Meta:
        verbose_name = "Пост"
        verbose_name_plural = "Посты"

    def __str__(self):
        return self.title
        # Create your models here.

users/models.py
from django.db import models

# Create your models here.

blog/forms.py
from django import forms
from django.contrib.auth.models import User
from .models import Post


class PostForm(forms.Form):
    title = forms.CharField(max_length=200,label="Заголовок")
    text = forms.CharField(widget=forms.Textarea,label="Текст поста")
    author = forms.ModelChoiceField(queryset=User.objects.all(), label="Автор")
    image = forms.ImageField(required=False,label="Изображение")

class NewPostForm(forms.ModelForm):
    class Meta:
        model = Post
        fields = ('title', 'text')

        labels ={
            'title': 'Заголовок',
            'text': 'Текст поста'
        }

users/forms.py
from django import forms
from  django.contrib.auth.forms import UserCreationForm
from django.contrib.auth.models import User



class RegistrationForm(UserCreationForm):
    username = forms.CharField(label="Логин", error_messages={"required":"Пожалуйста, введите логин"})
    first_name = forms.CharField(label="Имя")
    last_name = forms.CharField(label="Фамилия")
    email = forms.EmailField(label="Эл. почта")
    password1 = forms.CharField(label="Пароль", widget=forms.PasswordInput)
    password2 = forms.CharField(label="Подтвердите пароль",widget=forms.PasswordInput, error_messages={"required":"Пожалуйста, подтвердите пароль"})


    class Meta:
        model = User
        fields = ("username","first_name","last_name","email","password1","password2")

class NewRegistrationForm(forms.ModelForm):
    password2 = forms.CharField(label="Подтвердите пароль", widget=forms.PasswordInput)

    class Meta:
        model = User
        fields = ("username","first_name","last_name","email","password")
        help_text = {"usersname":"",}
        # labels = {
        #     "usersname":"XXX",
        # }
    def clean_password2(self):
        cleaned_data = self.cleaned_data
        if cleaned_data['password'] != cleaned_data ['password2']:
            raise forms.ValidationError("Пароли не совпадают!")
        return cleaned_data["password2"]

blog/views.py
from django.shortcuts import render, redirect, get_object_or_404
from .models import Post
from .forms import PostForm

def index(request):
    #Получение всех постов(select * from blog_post)
    posts = Post.objects.all()
    context =  {"title": "Главная страница", "posts":posts}
    return render(request,template_name='blog/index.html', context=context)

def about(request):
    context = {"title": "О сайте"}
    return render(request, template_name='blog/about.html', context=context)

def about_blog(request):
    context = {"title": "О Блоге"}
    return render(request, template_name='blog/about_blog.html', context=context)

def add_post(request):
    if request.method == 'GET':
        post_form = PostForm()
        context = {"title":"Добавить пост",'form': post_form}
        return render(request, template_name='blog/post_add.html', context=context)

    if request.method == 'POST':
        post_form = PostForm(data=request.POST, files=request.FILES)
        if post_form.is_valid():
            post = Post()
            post.title = post_form.cleaned_data['title']
            post.text = post_form.cleaned_data['text']
            post.author = post_form.cleaned_data['author']
            post.image = post_form.cleaned_data['image']
            post.save()
            return index(request)

def read_post(request, slug):
    #post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, slug=slug)
    context = {"title":"Информация о посте","post": post}
    return render(request, template_name="blog/post_detail.html", context=context)

def update_post(request, pk):
    #post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    if request.method == "POST":
        post_form = PostForm(data=request.POST, files=request.FILES)
        if post_form.is_valid():
            post.title = post_form.cleaned_data['title']
            post.text = post_form.cleaned_data['text']
            post.author = post_form.cleaned_data['author']
            post.image = post_form.cleaned_data['image']
            post.save()
            return redirect('blog:read_post', pk=post.id)
    else:
        post_form = PostForm(initial={
        "title": post.title,
        "author": post.author,
        "text": post.text,
        "image": post.image
        })
        return render(request, template_name="blog/post_edit.html", context={"form": post_form})

def delete_post(request, pk):
    #post = Post.objects.get(pk=pk)
    post = get_object_or_404(Post, pk=pk)
    context = {"post":post}
    if request.method == "POST":
        post.delete()
        return  redirect('blog:index')
    return render(request, template_name='blog/post_delete.html', context=context)

def page_not_found(request, exception):
    return render(request, template_name='blog/404.html', context={'title': "404"})

def forbidden(request, exception):
    return render(request, template_name="blog/403.html", context={'title': "403"})

def server_error(request):
    return render(request,template_name='blog/500.html', context={'title': "500"})

users/views.py
from django.shortcuts import render
from django.contrib.auth.forms import UserCreationForm
from .forms import RegistrationForm, NewRegistrationForm



def register(request):
    # Когда отправляем заполненую форму на сервер
    if request.method == "POST":
        # Создаем объект формы с данными из запроса
        form = NewRegistrationForm(request.POST)
        # Если форма валидна
        if form.is_valid():
            # Создаем объект пользователя без записи в БД
            new_user = form.save(commit=False)
            # Хэшируем пароль при помощи set_password
            new_user.set_password(form.cleaned_data['password'])
            # Сохраняем пользователя и БД
            new_user.save()
            context = {"title": "Регистрация завершена", "new_user":new_user}
            return render(request,template_name="users/registration_done.html", context=context)
    # Если метод GET(страница с пустой формой регистрации)
    form = NewRegistrationForm()
    context = {"title": "Регистрация пользователя", "register_form":form}
    return render(request,template_name="users/registration.html", context=context)


def log_in(request):
    pass

def log_out(request):
    pass

def user_profile(request, pk):
    pass

blog/templates/blog/about.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>О сайте</h1>
{% endblock content %}

blog/templates/blog/about_blog.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}

{% endblock content %}

blog/templates/blog/base.html
{% load static %}
<!DOCTYPE html>
<html lang="ru">
<head>
    <meta charset="utf-8">
    <title>{{title}}</title>
    <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@400;500;700&display=swap" rel="stylesheet">
    <link rel="stylesheet" type="text/css" href="{% static 'css/style.css' %}">
</head>
<body>
     <nav class="nav">
        <div class="container">
            <div class="logo">
                <a href="#"><img src="{% static 'img/_LOGO_PNG_WHITE_.png' %}"  height="60" width="auto"></a>
            </div>
            <div id="mainListDiv" class="main_list">
                <ul class="navlinks">
                    <li><a href="#Text">О Блоге</a></li>
                    <li><a href="{% url 'blog:add_post' %}">Посты</a></li>
                    <li><a href="#">Объявления</a></li>
                    <li><a href="#">Контакты</a></li>
                </ul>
            </div>
            <span class="navTrigger">
                <i></i>
                <i></i>
                <i></i>
            </span>
        </div>
    </nav>

    <section class="home">
        <div class="slider">
            <div class="slides">
                <div class="slide active">
                    <img src="{% static 'img/Фото_1.jpg' %}" alt="Картинка 1">
                </div>
                <div class="slide">
                    <img src="{% static 'img/Фото_2.jpg' %}" alt="Картинка 2">
                </div>
                <div class="slide">
                    <img src="{% static 'img/Фото_3.jpg' %}" alt="Картинка 3">
                </div>
            </div>
        </div>
        <script src="script.js"></script>
    </section>
			<h2 id="Text" class="myH2">Зачем блог?</h2>
			<h1><p class="myP">Для начала:</p></h1>
				<p class="myP">
                    1. Информирование читателей о музыкальных новинках и трендах. Автор блога может делиться свежими релизами, обзорами на альбомы и синглы, а также рассказывать о наиболее интересных событиях в мире музыки.
			    </p>
                <p class="myP">
                    2.  Обсуждение музыкальных жанров и стилей. В блоге можно анализировать различные музыкальные жанры, стили и направления, помогая читателям лучше понять и оценить разнообразие музыки.
			    </p>
                <p class="myP">
                    3. Представление и обсуждение творчества музыкантов и групп. Автор может рассказывать о жизни и творчестве известных музыкантов, а также открывать новых талантливых исполнителей.
			    </p>
                <p class="myP">
                    4. Проведение музыкальных обзоров и рецензий. Блог может стать площадкой для профессиональных музыкальных обзоров, что будет полезно для любителей музыки, желающих глубже погрузиться в анализ музыкальных произведений.
                </p>
                <p class="myP">
                    5. Обмен мнениями и дискуссия. Блог предоставляет возможность читателям делиться своими мнениями о музыке, участвовать в дискуссиях и обсуждениях, что способствует формированию музыкального сообщества.
                </p>
                <p class="myP">
                    6. Помощь в выборе музыки. Читатели могут найти в блоге рекомендации по музыке в соответствии со своими предпочтениями, что облегчит им поиск новых музыкальных произведений для прослушивания.
                </p>
                <p class="myP">
                    7. Поддержка и продвижение независимых музыкантов. Блог может стать платформой для молодых и независимых исполнителей, помогая им привлечь внимание к своему творчеству.
                </p>
                <p class="myP">
                    8. Создание музыкального сообщества. Блог может объединить людей с общими интересами, способствуя созданию музыкального сообщества, где участники могут делиться своими мыслями, рекомендациями и открытиями.
                </p>
                <p class="myP">
                    9. Образовательная функция. В блоге можно публиковать статьи о теории музыки, истории музыкальных жанров, а также давать советы по развитию музыкальных навыков.
                </p>
                <p class="myP">
                    10. Вдохновение и мотивация. Блог может стать источником вдохновения для читателей, интересующихся музыкой, и помочь им найти свой уникальный музыкальный стиль.
                </p>
    </div>
    <script src="https://ajax.googleapis.com/ajax/libs/jquery/3.1.1/jquery.min.js"></script>
     <script src="{% static 'js/script.js' %}"></script>
{% block content %}
{% endblock content%}
</body>
</html>

blog/templates/blog/index.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}
<div>
    <div class="post-list">
{% for post in posts %}
        <div class="post-item">
            {% if post.image %}
                <img src="{{ post.image.url }}" width="200px" height="auto">
            {% else %}
                <img src="{% static 'img/No.jpg' %}" width="200" height="auto">
            {% endif %}
            <div>
                <div class="post-author">
                    <h3><b>{{ post.author }}</b></h3>
                </div>
                <div class="post-title">
                    <p><h4><a href="{{ 'post.get_absolute_url' }}">{{ post.title }}</a></h4></p>
                </div>
                <div class="post-text">
                    <p> {{ post.text }} </p>
                </div>
                <div class="created_at">
                    <p><i>{{ post.created_at }}</i></p>
                </div>
{% endfor %}
</div>

{% endblock content %}

blog/templates/blog/post_add.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Добавить новый пост</h1>
<form action="" method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Добавить пост</button>
</form>

{% endblock content %}

blog/templates/blog/post_delete.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Удалить пост</h1>
<p>Автор - {{ post.author }}</p>
<p>Загаловок - {{ post.title }}</p>

<form method="post">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Удалить</button>
    <a href="{% url 'blog:index' %}">
        <button type="button">Отменить</button>
    </a>
</form>

{% endblock content %}

blog/templates/blog/post_detail.html
{% extends 'blog/base.html' %}
{% load static %}
{% block content %}


<h3>Информация о посте № {{ post.pk }}</h3>
<hr>
<b>{{ post.author }}</b>
<h4>{{ post.title }}</h4>
{% if post.image %}
    <img src="{{ post.image.url }}" width="200px" height="auto">
{% else %}
    <img src="{% static 'img/No.jpg' %}" width="200" height="auto">
{% endif %}
<br>
{{ post.text }}
<p><i>{{ post.created_at }}</i></p>
<div class="bt-actions">
    <div class="bth-edit-post">
        <a href="{% url 'blog:update_post' pk=post.id %}">
            <button type="button">Редактировать</button>
        </a>
    </div>
    <div class="bth-del-post">
        <a href="{% url 'blog:delete_post' pk=post.id %}">
            <button type="button">Удалить</button>
        </a>
    </div>
</div>


{% endblock content %}

blog/templates/blog/post_edit.html
{% extends 'blog/base.html' %}

{% block content %}
<h1>Редактировать пост</h1>
<form action="" method="post" enctype="multipart/form-data">
    {% csrf_token %}
    {{ form.as_p }}
    <button type="submit">Изменить пост</button>
</form>

{% endblock content %}

users/templates/users/registration.html
{% extends 'blog/base.html' %}

{% block content %}
<h3>Регистрация пользователя</h3>
<form method="post">
    {% csrf_token %}
    {{ register_form }}
    <button type="submit">Зарегистрироваться</button>
</form>

{% endblock content %}